# Generated by Django 2.1 on 2018-08-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_password',
        ),
    ]
