# Generated by Django 2.1 on 2018-08-01 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vita', '0002_auto_20180802_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 16, 9, 31, 765402, tzinfo=utc)),
        ),
    ]
